---
- name: Add hosts file to managed servers
  hosts: all
  tasks:
    - name: Copy /etc/hosts file from control to manage nodes
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /etc/hosts
        owner: root
        group: root
    - name: Install the latest version of Python3
      ansible.builtin.dnf:
        name: python3
        state: latest
